// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE5dYwCFetwUOTqLvpCiUXQXG-rcyPB1I',
    appId: '1:177722519530:web:6c3ef601e76d085f1acc93',
    messagingSenderId: '177722519530',
    projectId: 'fullcrud-31cf3',
    authDomain: 'fullcrud-31cf3.firebaseapp.com',
    storageBucket: 'fullcrud-31cf3.appspot.com',
    measurementId: 'G-BC521WC24F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlH6QEKR6IB_2O37MehsuQc7JOwLkp8Tw',
    appId: '1:177722519530:android:0499a22483b2b2231acc93',
    messagingSenderId: '177722519530',
    projectId: 'fullcrud-31cf3',
    storageBucket: 'fullcrud-31cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcYJ7LdG8ESa4su7qcHJEiUR-RvmSLpw',
    appId: '1:177722519530:ios:2c7a8c1199cf84b81acc93',
    messagingSenderId: '177722519530',
    projectId: 'fullcrud-31cf3',
    storageBucket: 'fullcrud-31cf3.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcYJ7LdG8ESa4su7qcHJEiUR-RvmSLpw',
    appId: '1:177722519530:ios:6ba766ff81c94a871acc93',
    messagingSenderId: '177722519530',
    projectId: 'fullcrud-31cf3',
    storageBucket: 'fullcrud-31cf3.appspot.com',
    iosBundleId: 'com.example.eproject.RunnerTests',
  );
}
